export const action = {
  FIRTS: 'FIRST',
  ERROR: 'ERROR',

  SECOND_START: 'SECOND_START',
  SECOND_ERROR: 'SECOND_ERROR',
  SECOND_RECIVE: 'SECOND_RECIVE',
  SECOND_RETURN_START: 'SECOND_RETURN_START',

  THREE_START: 'THREE_START',
  THREE_ERROR: 'THREE_ERROR',
  THREE_RECIVE: 'THREE_RECIVE',
  THREE_RETURN_START: 'THREE_RETURN_START'
}